stages:
- deploy

deploy-to-aur:
  stage: deploy
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  only:
  - tags@heimbach/yacl
  script:
  - mkdir --mode=700 ~/.ssh/
  - (umask 0377 && echo "$AUR_PRIVATE_KEY" > ~/.ssh/id_rsa
                && echo "aur.archlinux.org $AUR_HOST_KEY" >> ~/.ssh/known_hosts)
  - git clone "ssh://aur@aur.archlinux.org/python-yacl.git" "python-yacl-aur"
  - cd "python-yacl-aur"
  - sed -i -e "/^pkgver=/c\pkgver=\"${CI_COMMIT_TAG#v}\"" -e "/^pkgrel=/c\pkgrel=\"1\"" PKGBUILD
  - (
      source PKGBUILD;
      curl -o source -L "${source[0]}";
      SHA256SUM="$(sha256sum source | awk '{ print $1 }')";
      sed -i "/^sha256sums=/c\sha256sums=(\"${SHA256SUM}\")" PKGBUILD;
    )
  - makepkg --printsrcinfo > .SRCINFO
  - git commit -a -m "Update to version ${CI_COMMIT_TAG#v}"
  - git push
